server:
  port: 2002

spring:
  profiles:
    active: common
  application:
    name: seata-storage-service
  cloud:
    alibaba:
      seata:
        tx-service-group: default
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: BiGData922
    url: jdbc:mysql://192.168.223.128:3306/seata_storage?serverTimezone=Hongkong&characterEncoding=utf-8&useSSL=false
    hikari:
      maximum-pool-size: 10
      connection-test-query: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource


feign:
  hystrix:
    enabled: false
logging:
  level:
    io:
      seata: info



seata:
  application-id: ${spring.application.name}
  enabled: true
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: true
  config:
    type: nacos
    nacos:
      server-addr: localhost:8848
      group: SEATA_GROUP
      username: "nacos"
      password: "nacos"
      namespace:
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: localhost:8848
      username: "nacos"
      password: "nacos"
      namespace:
