server:
  port: 8001

eureka:
  client:
    register-with-eureka: true   #是否将自己注册到注册中心,集群必须设置为true配合ribbon
    fetch-registry: true    #是否从服务端抓取已有的注册信息
    service-url:
      defaultZone: http://localhost:7001/eureka # ,http://eureka7002.com:7002/eureka

spring:
  application:
    name: cloud-provider-hystrix-payment
  profiles:
    active: common
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: BiGData922
    url: jdbc:mysql://192.168.223.128:3306/bigdata?serverTimezone=Hongkong&characterEncoding=utf-8&useSSL=false
    hikari:
      maximum-pool-size: 10
      connection-test-query: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource
