server:
  port: 80

spring:
  application:
    name: cloud-consumer-feign-hystrix-service
  profiles:
    active: common
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.223.128:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: BiGData922

eureka:
  client:
    register-with-eureka: true   #是否将自己注册到注册中心,集群必须设置为true配合ribbon
    fetch-registry: true    #是否从服务端抓取已有的注册信息
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: cloud-consumer-service80
    prefer-ip-address: true   #访问路径可以显示IP地址
##设置feign客户端超时时间
ribbon:
  ReadTimeout: 1000
  ConnectTimeout: 1000
feign:
  hystrix:
    enabled: true